BASE <http://purl.regenstrief.org/NDPBRN/dental-practice/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX pbrn_id: <http://purl.obolibrary.org/obo/OHD_0000273>
PREFIX sesame: <http://www.openrdf.org/schema/sesame#>
PREFIX patient: <http://purl.obolibrary.org/obo/OHD_0000012>
PREFIX tooth: <http://purl.obolibrary.org/obo/FMA_12516>
PREFIX ada_num: <http://purl.obolibrary.org/obo/OHD_0000065>
PREFIX part_of: <http://purl.obolibrary.org/obo/BFO_0000050>
PREFIX prop: <http://purl.regenstrief.org/NDPBRN/property/>

select distinct ?practice ?patient_id ?tooth_id ?tooth_num ?first_PCR ?first_RCT ?extract_date ?missing_date
where {
    ## find instance of patient and patient's DOB
    ?patient_i 
        a patient:;
        pbrn_id: ?pbrn_id .
    
    ## find patients' teeth
    ?tooth_i
        a tooth:;
        prop:ada_tooth_number ?tooth_num;
        part_of: ?patient_i .
    
    ## find first PCR/RCT dates
    optional { ?tooth_i prop:first_PCR_date ?first_PCR . }
	  optional { ?tooth_i prop:first_RCT_date ?first_RCT .}
	
    ## find date (if any) the tooth was extracted
    #?tooth_i prop:extraction_date ?extract_date . # used for testing
    optional {
        ?tooth_i prop:extraction_date ?extract_date .
    }
    
    ## find date (if any) tooth was found to be missing
    #?tooth_i prop:missing_tooth_finding_date ?missing_date . # used for testing
    optional {
        ?tooth_i prop:missing_tooth_finding_date ?missing_date .
    }
    
    bind(strafter(str(?pbrn_id), "NDPBRN practice ") as ?practice)
    bind(strafter(str(?patient_i), "patient/") as ?patient_id)
    bind(strafter(str(?tooth_i), "tooth/") as ?tooth_id)
}
#limit 100